# Generated by Django 3.2.8 on 2022-06-01 15:01

import datetime
from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('author', models.TextField()),
                ('footnote', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='images/', validators=[home.validators.validate_file_extension])),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('author', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=2000)),
                ('price', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('orderstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('bread', 'bread'), ('cakes', 'cakes'), ('pastries', 'pastries'), ('cookies', 'cookies')], max_length=200)),
                ('subcategory', models.CharField(blank=True, choices=[('white', 'white'), ('bagel', 'bagel'), ('whole wheat', 'whole wheat'), ('sourdough', 'sourdough'), ('rye', 'rye'), ('multigrain', 'multigrain'), ('eggdough', 'eggdough')], max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('image', models.FileField(upload_to='images/', validators=[home.validators.validate_file_extension])),
            ],
        ),
    ]
